name: "Check uncommitted changes"
description: "Checks if a git repository has uncommitted changes"
branding:
  icon: "alert-circle"
  color: "yellow"
outputs:
  changes:
    description: "Uncommitted changes if any"
runs:
  using: "docker"
  image: "Dockerfile"
